language: node_js
node_js:
  - "10"
script:
 - echo "Build and deploy!!"
 - npm install
 - npm run build
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --project vaaligone --token "$FIREBASE_TOKEN"
